"""Global info method types.

DEPRECATED: This module is deprecated. Import from hotstuff.methods.info.market instead.
This module exists for backward compatibility only.
"""
# Re-export everything from market.py for backward compatibility
from hotstuff.methods.info.market import (
    OracleParams,
    OracleResponse,
    SupportedCollateralParams,
    BridgeByChain,
    WeightTier,
    CollRisk,
    SupportedCollateral,
    InstrumentsParams,
    MarginTier,
    PerpInstrument,
    SpotInstrument,
    InstrumentsResponse,
    TickerParams,
    Ticker,
    OrderbookParams,
    OrderbookLevel,
    OrderbookResponse,
    TradesParams,
    Trade,
    MidsParams,
    Mid,
    BBOParams,
    BBO,
    SupportedChartResolutions,
    SupportedChartTypes,
    ChartParams,
    ChartPoint,
)

__all__ = [
    "OracleParams",
    "OracleResponse",
    "SupportedCollateralParams",
    "BridgeByChain",
    "WeightTier",
    "CollRisk",
    "SupportedCollateral",
    "InstrumentsParams",
    "MarginTier",
    "PerpInstrument",
    "SpotInstrument",
    "InstrumentsResponse",
    "TickerParams",
    "Ticker",
    "OrderbookParams",
    "OrderbookLevel",
    "OrderbookResponse",
    "TradesParams",
    "Trade",
    "MidsParams",
    "Mid",
    "BBOParams",
    "BBO",
    "SupportedChartResolutions",
    "SupportedChartTypes",
    "ChartParams",
    "ChartPoint",
]
